Starting from step 0
Training for 4001 steps
10 31.758484840393066
20 51.61209750175476
30 71.57134509086609
40 91.4937162399292
50 114.87910318374634
60 135.33741998672485
70 155.20179080963135
80 175.03036165237427
90 194.31029796600342
100 218.0763599872589
110 237.77043080329895
120 257.51736640930176
130 277.2878968715668
140 300.72350311279297
150 321.0348582267761
160 340.65560007095337
170 360.63921999931335
180 380.1032269001007
190 403.85389018058777
200 423.92872762680054
210 446.2093622684479
220 470.6445801258087
230 495.0100905895233
240 525.6302015781403
250 552.7622895240784
260 578.3124051094055
270 597.9903988838196
280 621.6417779922485
290 641.1744954586029
300 Loss: 451.28
In Logging <wandb.sdk.wandb_run.Run object at 0x7f71003527c0> 0
300 664.2668747901917
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/serialization.py", line 604, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
OSError: [Errno 28] No space left on device
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ec2-user/attribute_probe/clip_src/training_scripts/CLIP_text_image_concat/train_clip_text_image_concat.py", line 390, in <module>
    trainer.train()
  File "/home/ec2-user/attribute_probe/clip_src/training_scripts/trainer.py", line 89, in train
    torch.save({
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/serialization.py", line 380, in save
    return
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/serialization.py", line 259, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:319] . unexpected pos 1002902464 vs 1002902356